### ISSUE TITLE
checkpoints can't download from google drive.

### ISSUE THREAD

**Issue by YOOHYOJEONG** [Onehour0108/MitDet#1]
Hi. 

The Google Drive link for checkpoints you uploaded is not working properly.
The link to the Google drive is connected to the mitdet repository. (baidu cloud link too.)

![image](https://github.com/Onehour0108/MitDet/assets/86641457/f6229756-d768-442e-a0ad-b1a386b4ead9)   

And there are no files in the checkpoints folder.   

How do I download checkpoints?

Thank you.

**Comment by Onehour0108** [comment]
Our paper is still under review. Once the paper is accepted, we will provide the training code and checkpoints.

**Comment by YOOHYOJEONG** [comment]
Okay. Thank you :)
